service: serverless-sqs-dynamodb
frameworkVersion: "2"

custom:
  sqsArn:
    Fn::ImportValue: S3QueueArn

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-central-1
  memorySize: 128
  lambdaHashingVersion: 20201221
  environment: ${file(../../serverless.common.yml):environment}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
        - Effect: Allow
          Action:
            - "sqs:*"
          Resource: ${self:custom.sqsArn}

functions:
  sqsDynamodb:
    handler: lambda_handler.sqs_dynamodb
    events:
      - sqs:
          arn: ${self:custom.sqsArn}
          batchSize: 1
